image: alpine

documentation:
  before_script:
  - apk update
  - apk add doxygen
  - apk add ttf-freefont graphviz
  script:
  - doxygen Doxyfile_CI
  only:
  - develop
  
pages:
  script:
  - doxygen Doxyfile
  - mv docs/ public/
  artifacts:
    paths:
    - public
  only:
  - master

code_style:
  before_script:
  - apk update
  - apk add py-pip
  - pip install pycodestyle
  script:
  - pycodestyle --ignore=E501 main calendars notes todo
  only:
  - develop
