image: alpine

before_script:
- apk update
- apk add doxygen
- apk add ttf-freefont graphviz

test:
  script:
  - doxygen Doxyfile
  except:
  - master
  
pages:
  script:
  - doxygen Doxyfile
  - mv docs/ public/
  artifacts:
    paths:
    - public
  only:
  - master
