image: ubuntu

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - apt-get update
  - apt-get install -y python3-pip
  - pip3 install -r requirements.txt

documentation:
  before_script:
  - apt-get update
  - apt-get install -y doxygen ttf-freefont graphviz
  script:
  - doxygen Doxyfile_CI
  only:
  - develop
  
pages:
  before_script:
  - apt-get update
  - apt-get install -y doxygen ttf-freefont graphviz
  script:
  - doxygen Doxyfile
  - mv docs/ public/
  artifacts:
    paths:
    - public
  only:
  - develop

code_style:
  script:
  - pycodestyle --ignore=E501,E265 main calendars notes todo
  only:
  - develop

test:
  script:
  - python manage.py test --settings=morris_butler.settings_ci
  only:
  - develop
