image: alpine

before_script:
- apk update
- apk add doxygen
- apk add ttf-freefont graphviz
- apk add py-pip
- pip install pycodestyle


documentation:
  script:
  - doxygen Doxyfile
  only:
  - develop

code_style:
  script:
  - pycodestyle --ignore=E501 main calendars notes todo
  only:
  - develop
