image: alpine

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - apk update
  - apk add py-pip
  - pip install -r requirements.txt

documentation:
  before_script:
  - apk update
  - apk add doxygen
  - apk add ttf-freefont graphviz
  script:
  - doxygen Doxyfile_CI
  only:
  - develop
  
pages:
  before_script:
  - apk update
  - apk add doxygen
  - apk add ttf-freefont graphviz
  script:
  - doxygen Doxyfile
  - mv docs/ public/
  artifacts:
    paths:
    - public
  only:
  - develop

code_style:
  script:
  - pycodestyle --ignore=E501,E265 main calendars notes todo
  only:
  - develop

test:
  script:
  - python manage.py test
  only:
  - develop
